// Code generated by protoc-gen-go. DO NOT EDIT.
// source: regionagogosvc.proto

/*
Package regionagogosvc is a generated protocol buffer package.

It is generated from these files:
	regionagogosvc.proto

It has these top-level messages:
	Point
	RegionResponse
*/
package regionagogosvc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Point struct {
	Latitude  float32 `protobuf:"fixed32,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float32 `protobuf:"fixed32,2,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Point) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Point) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type RegionResponse struct {
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
}

func (m *RegionResponse) Reset()                    { *m = RegionResponse{} }
func (m *RegionResponse) String() string            { return proto.CompactTextString(m) }
func (*RegionResponse) ProtoMessage()               {}
func (*RegionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegionResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func init() {
	proto.RegisterType((*Point)(nil), "regionagogosvc.Point")
	proto.RegisterType((*RegionResponse)(nil), "regionagogosvc.RegionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RegionAGogo service

type RegionAGogoClient interface {
	// Obtains the region at a given position.
	GetRegion(ctx context.Context, in *Point, opts ...grpc.CallOption) (*RegionResponse, error)
}

type regionAGogoClient struct {
	cc *grpc.ClientConn
}

func NewRegionAGogoClient(cc *grpc.ClientConn) RegionAGogoClient {
	return &regionAGogoClient{cc}
}

func (c *regionAGogoClient) GetRegion(ctx context.Context, in *Point, opts ...grpc.CallOption) (*RegionResponse, error) {
	out := new(RegionResponse)
	err := grpc.Invoke(ctx, "/regionagogosvc.RegionAGogo/GetRegion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RegionAGogo service

type RegionAGogoServer interface {
	// Obtains the region at a given position.
	GetRegion(context.Context, *Point) (*RegionResponse, error)
}

func RegisterRegionAGogoServer(s *grpc.Server, srv RegionAGogoServer) {
	s.RegisterService(&_RegionAGogo_serviceDesc, srv)
}

func _RegionAGogo_GetRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Point)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionAGogoServer).GetRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/regionagogosvc.RegionAGogo/GetRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionAGogoServer).GetRegion(ctx, req.(*Point))
	}
	return interceptor(ctx, in, info, handler)
}

var _RegionAGogo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "regionagogosvc.RegionAGogo",
	HandlerType: (*RegionAGogoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRegion",
			Handler:    _RegionAGogo_GetRegion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "regionagogosvc.proto",
}

func init() { proto.RegisterFile("regionagogosvc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x4a, 0x4d, 0xcf,
	0xcc, 0xcf, 0x4b, 0x4c, 0xcf, 0x4f, 0xcf, 0x2f, 0x2e, 0x4b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x43, 0x15, 0x55, 0x72, 0xe4, 0x62, 0x0d, 0xc8, 0xcf, 0xcc, 0x2b, 0x11, 0x92, 0xe2,
	0xe2, 0xc8, 0x49, 0x2c, 0xc9, 0x2c, 0x29, 0x4d, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0a,
	0x82, 0xf3, 0x85, 0x64, 0xb8, 0x38, 0x73, 0xf2, 0xf3, 0xd2, 0x21, 0x92, 0x4c, 0x60, 0x49, 0x84,
	0x80, 0x92, 0x0a, 0x17, 0x5f, 0x10, 0xd8, 0xd0, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54,
	0x21, 0x21, 0x2e, 0x96, 0xe4, 0x7c, 0xa8, 0x39, 0x9c, 0x41, 0x60, 0xb6, 0x51, 0x30, 0x17, 0x37,
	0x44, 0x95, 0xa3, 0x7b, 0x7e, 0x7a, 0xbe, 0x90, 0x0b, 0x17, 0xa7, 0x7b, 0x6a, 0x09, 0x44, 0x44,
	0x48, 0x54, 0x0f, 0xcd, 0xad, 0x60, 0x27, 0x49, 0xc9, 0xa1, 0x0b, 0xa3, 0x5a, 0xa3, 0xc4, 0x90,
	0xc4, 0x06, 0xf6, 0x94, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x12, 0x22, 0x2b, 0xec, 0x00,
	0x00, 0x00,
}
